apiVersion: v1
kind: Service
metadata:
  name: backstage
  namespace: backstage
spec:
  selector:
    app: backstage
  ports:
    - name: backend
      port: 7007
      targetPort: 7007
    - name: frontend
      port: 3000
      targetPort: 3000
